---
mary-tts:
  module-path: http://127.0.0.1:8080/mary-tts/
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: synthesis_server
    url: jdbc:mysql://localhost:3306/srp
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update


---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: synthesis_server
    url: jdbc:mysql://192.168.1.53:3306/srp
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0